### PR TITLE
[Feature] NPC Performance

### PR DESCRIPTION
**Pull request by kyleady**
This feature replaces `.getDocuments()` with [`.getIndex()`](https://foundryvtt.com/api/CompendiumCollection.html#getIndex) to increase NPC filter performance. The method `.getIndex()` allows us to only request information necessary for filtering, reducing the memory cost. Further, it only needs to be constructed when new information is required for filtering, reducing the filtering times when no new information is required, such as trying out different spellings when querying NPCs by name.

### Example
**NPCs**: Four compendiums of 2164, 319, 394, and 487 NPCs.
**Query**: Name contains "Vampir"
**Result**: 24 NPCs. All compendiums had to be filtered.

**Old Performance**:  `loadAndFilterNpcs: 22951.043212890625 ms`
**New Performance**: `loadAndFilterNpcs: 444.22802734375 ms`
**Comparison**: 98% reduction in query time.

### Note

Switching over to LF line endings obscures the changes in this PR. Please see the [Use .getIndex()](https://github.com/League-of-Foundry-Developers/compendium-browser/commit/8dd84954d50cc6fb393ef9deca8d62f9c467c6dd) commit to see the relevant changes.

### CODE REVIEW

**Comment by kyleady** [comment]
A [commit](https://github.com/League-of-Foundry-Developers/compendium-browser/commit/62c64e432f9ce51581d97a0c0590195a9e9c0383) was pushed within 2 minutes of when I made this PR. Will adjust and test.

**Comment by kyleady** [comment]
compendium-browser v0.7.2 merged in and tested on
* Foundry 0.8.9, DnD 1.5.6
* Foundry v9-Build 238, DnD 1.5.6

**Review by spetzel2020 — APPROVED** [review]

**Review by spetzel2020 — COMMENTED** [review]
My reading of your comment about LF endings is that I should merge the other two commits, but not this one - correct?

**Review by spetzel2020 — APPROVED** [review]

**Comment by kyleady** [comment]
They would all be merged. However, I can remake the PR without any merging or line ending changes.

**Comment by spetzel2020** [comment]
> They would all be merged. However, I can remake the PR without any merging or line ending changes.

That would be great; I'd rather not put in a mass change like that. For my edification, why the change to LF endings - is that just a stylistic choice?

**Comment by kyleady** [comment]
The repository is a mix of files where some are LF and some are CRLF. It was more of a matter of trying to pick one and simplify.

Closing this one and will make a new PR, probably tomorrow.

**Pull request closed without merging**
